services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka_broker:
    container_name: kafka_broker
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    env_file:
      - .env
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # by default listen all
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d  # init scripts

  kafka_producer:
    container_name: kafka_producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - kafka_broker
    env_file:
      - .env

  spark_consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: spark_consumer
    depends_on:
      - kafka_producer
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8888:8888"  # port to run jobs in Jupyter

volumes:
  kafka_data:
  postgres_data:
  spark_jars: