version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BROKER}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - ${PROJECT_ABS_PATH}/kafka_data:/var/lib/kafka/data
    env_file:
      - .env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${PROJECT_ABS_PATH}/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  spark:
    image: bitnami/spark:latest
    depends_on:
      - kafka
    environment:
      SPARK_MODE: "master"
      SPARK_MASTER_URL: "spark://spark:7077"
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file:
      - .env

volumes:
  postgres_data:
  kafka_data: